import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, getDocs, query, orderBy, serverTimestamp, deleteDoc } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-storage.js";

const HUB_URL="https://eliezelapolinaris2017-lab.github.io/oasis-hub/";
const firebaseConfig={apiKey:"AIzaSyBm67RjL0QzMRLfo6zUYCI0bak1eGJAR-U",authDomain:"oasis-facturacion.firebaseapp.com",projectId:"oasis-facturacion",storageBucket:"oasis-facturacion.firebasestorage.app",messagingSenderId:"84422038905",appId:"1:84422038905:web:b0eef65217d2bfc3298ba8"};
const fb=initializeApp(firebaseConfig), auth=getAuth(fb), db=getFirestore(fb), storage=getStorage(fb);
const $=id=>document.getElementById(id);
const money=n=>Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const today=()=>new Date().toISOString().slice(0,10);
const uid=(p="id")=>`${p}_${Date.now()}_${Math.random().toString(16).slice(2)}`;
const clean=s=>String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim();
function isIOS(){return /iPhone|iPad|iPod/i.test(navigator.userAgent||"");}
function base(uid){return `users/${uid}`}
function docsCol(uid){return collection(db,`${base(uid)}/docs`)}
function customersCol(uid){return collection(db,`${base(uid)}/customers`)}
function sharedCol(uid){return collection(db,`${base(uid)}/shared_customers/items`)}
function crmCol(uid){return collection(db,`${base(uid)}/oasis_crm_v3/clients/items`)}
function settingsRef(uid){return doc(db,`${base(uid)}/settings/main`)}

let state={user:null,view:"dashboard",current:null,docs:[],customers:[],shared:[],cfg:null,activeDocId:null};
function defaultCfg(){return{biz:{name:"",phone:"",email:"",addr:"",logoUrl:"",logoDataUrl:""},taxRate:11.5}}
function newDoc(){return{id:uid("doc"),type:"COT",number:"",date:today(),status:"PENDIENTE",client:{name:"",contact:"",addr:""},items:[{id:uid("it"),desc:"",qty:1,price:0}],notes:"",terms:"",taxRate:Number(state.cfg?.taxRate||11.5),totals:{sub:0,tax:0,grand:0},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
async function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function urlToDataUrl(url){const resp=await fetch(url,{cache:"no-store"}); const blob=await resp.blob(); return await fileToDataUrl(blob)}
function setAuthUI(){const on=!!state.user;$("btnLogin")?.classList.toggle("hidden",on);$("btnLogout")?.classList.toggle("hidden",!on);$("authState").textContent=on?`Online · ${state.user.email}`:"Offline"}
async function login(){const p=new GoogleAuthProvider(); if(isIOS()) await signInWithRedirect(auth,p); else await signInWithPopup(auth,p)}
async function logout(){await signOut(auth)}

function customerKey(c){return `${norm(c.name)}|${norm(c.contact)}`}
function normalizeCustomer(c={},src="manual"){return{id:String(c.id||uid("cus")),name:String(c.name||c.clientName||""),contact:String(c.contact||c.phone||c.email||""),addr:String(c.addr||c.address||""),note:String(c.note||""),source:c.source||src,updatedAt:c.updatedAt||c.createdAt||new Date().toISOString()}}
function mergedCustomers(){const map=new Map();[...state.shared,...state.customers].forEach(c=>{c=normalizeCustomer(c,c.source||"cliente"); if(!c.name) return; const k=customerKey(c); const old=map.get(k); if(!old||String(c.updatedAt)>String(old.updatedAt)) map.set(k,c)}); return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
async function upsertSharedCustomer(c){if(!state.user||!c?.name)return; const id=c.id||uid("cus"); const payload={...normalizeCustomer({...c,id},c.source||"invoicing"),updatedAt:serverTimestamp(),source:c.source||"invoicing"}; await Promise.all([setDoc(doc(db,`${base(state.user.uid)}/customers/${id}`),payload,{merge:true}),setDoc(doc(db,`${base(state.user.uid)}/shared_customers/items/${id}`),payload,{merge:true})])}
async function loadAll(){if(!state.user)return; const s=await getDoc(settingsRef(state.user.uid)); state.cfg=s.exists()?{...defaultCfg(),...s.data(),biz:{...defaultCfg().biz,...(s.data().biz||{})}}:defaultCfg(); if(state.cfg.biz.logoUrl&&!state.cfg.biz.logoDataUrl){try{state.cfg.biz.logoDataUrl=await urlToDataUrl(state.cfg.biz.logoUrl)}catch{}}
 const [ds,cs,ss]=await Promise.all([getDocs(query(docsCol(state.user.uid),orderBy("updatedAt","desc"))),getDocs(query(customersCol(state.user.uid),orderBy("updatedAt","desc"))),getDocs(sharedCol(state.user.uid))]);
 state.docs=ds.docs.map(d=>({id:d.id,...d.data()})); state.customers=cs.docs.map(d=>normalizeCustomer({id:d.id,...d.data()},"invoicing")); state.shared=ss.docs.map(d=>normalizeCustomer({id:d.id,...d.data()},"shared")); refreshAll();}
async function importCrmCustomers(){if(!state.user)return alert("Login requerido."); const snap=await getDocs(crmCol(state.user.uid)); let n=0; for(const d of snap.docs){const c=normalizeCustomer({id:`crm_${d.id}`,...d.data(),source:"crm"},"crm"); if(c.name){await upsertSharedCustomer(c); n++;}} await loadAll(); alert(`${n} clientes importados/sincronizados.`)}

function setView(v){state.view=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("is-active"));$("view-"+v)?.classList.add("is-active");document.querySelectorAll(".navBtn").forEach(b=>b.classList.toggle("is-active",b.dataset.view===v)); const names={dashboard:"Dashboard",editor:"Documento",customers:"Clientes",history:"Historial",settings:"Config"};$("pageTitle").textContent=names[v]||"Nexus"; if(v==="editor") syncForm(); refreshAll()}
function readForm(){const c=state.current||newDoc(); c.type=$("docType").value;c.number=$("docNumber").value.trim();c.date=$("docDate").value||today();c.status=$("docStatus").value;c.client={name:$("clientName").value.trim(),contact:$("clientContact").value.trim(),addr:$("clientAddr").value.trim()};c.notes=$("notes").value.trim();c.terms=$("terms").value.trim();c.taxRate=Number(state.cfg?.taxRate||$("taxRate")?.value||11.5); state.current=c; calcTotals()}
function syncForm(){const c=state.current||newDoc(); state.current=c; $("docType").value=c.type||"COT";$("docNumber").value=c.number||"";$("docDate").value=c.date||today();$("docStatus").value=c.status||"PENDIENTE";$("clientName").value=c.client?.name||"";$("clientContact").value=c.client?.contact||"";$("clientAddr").value=c.client?.addr||"";$("notes").value=c.notes||"";$("terms").value=c.terms||"";$("docMode").textContent=state.activeDocId?"Editando":"Nuevo";renderItems();calcTotals();renderDatalist()}
function renderDatalist(){const dl=$("customerNames"); if(!dl)return; dl.innerHTML=mergedCustomers().map(c=>`<option value="${clean(c.name)}"></option>`).join("")}
function useCustomerByName(){const name=$("clientName").value;const c=mergedCustomers().find(x=>norm(x.name)===norm(name)); if(c){$("clientContact").value=c.contact||"";$("clientAddr").value=c.addr||""}}
function renderItems(){const wrap=$("items"); if(!wrap)return; const items=state.current?.items||[]; wrap.innerHTML=""; items.forEach((it,i)=>{const row=document.createElement("div");row.className="itemRow";row.innerHTML=`<label>Descripción<input class="input itDesc" value="${clean(it.desc)}" placeholder="Servicio / producto"></label><label>Cant.<input class="input itQty" type="number" step="0.01" value="${Number(it.qty||1)}"></label><label>Precio<input class="input itPrice" type="number" step="0.01" value="${Number(it.price||0)}"></label><label>Total<input class="input" disabled value="${money(Number(it.qty||0)*Number(it.price||0))}"></label><button class="btn danger removeItem" type="button">Borrar</button>`; row.querySelectorAll("input").forEach(inp=>inp.addEventListener("input",()=>{it.desc=row.querySelector(".itDesc").value;it.qty=Number(row.querySelector(".itQty").value||0);it.price=Number(row.querySelector(".itPrice").value||0);calcTotals();renderItems()}));row.querySelector(".removeItem").onclick=()=>{state.current.items.splice(i,1); if(!state.current.items.length) state.current.items.push({id:uid("it"),desc:"",qty:1,price:0}); renderItems(); calcTotals()};wrap.appendChild(row)})}
function calcTotals(){const c=state.current;if(!c)return; const sub=(c.items||[]).reduce((a,it)=>a+Number(it.qty||0)*Number(it.price||0),0); const tax=sub*Number(c.taxRate||state.cfg?.taxRate||11.5)/100; c.totals={sub,tax,grand:sub+tax};$("subTotal").textContent=money(sub);$("taxTotal").textContent=money(tax);$("grandTotal").textContent=money(sub+tax)}
function nextNumber(type){const y=new Date().getFullYear();const p=type==="FAC"?"FAC":"COT";const re=new RegExp(`^${p}-${y}-(\\d{4})$`);let max=0;state.docs.forEach(d=>{const m=String(d.number||"").match(re);if(m)max=Math.max(max,Number(m[1]))});return `${p}-${y}-${String(max+1).padStart(4,"0")}`}
async function saveDoc({forceNumber=false}={}){if(!state.user)return alert("Login requerido.");readForm(); if(!state.current.client.name)return alert("Cliente requerido."); if(forceNumber||!state.current.number) state.current.number=nextNumber(state.current.type); const now=new Date().toISOString();state.current.updatedAt=now;if(!state.current.createdAt)state.current.createdAt=now; const payload=JSON.parse(JSON.stringify(state.current));payload.updatedAt=serverTimestamp(); await setDoc(doc(db,`${base(state.user.uid)}/docs/${state.current.id}`),payload,{merge:true}); await upsertSharedCustomer({...state.current.client,source:"documento"}); state.activeDocId=state.current.id; await loadAll(); syncForm()}
async function deleteCurrentDoc(){if(!state.user||!state.activeDocId)return alert("No hay documento seleccionado."); if(!confirm("¿Borrar documento?"))return; await deleteDoc(doc(db,`${base(state.user.uid)}/docs/${state.activeDocId}`)); state.current=newDoc();state.activeDocId=null;await loadAll();syncForm();setView("editor")}
function duplicateDoc(){readForm();state.current={...JSON.parse(JSON.stringify(state.current)),id:uid("doc"),number:"",status:"PENDIENTE",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.activeDocId=null;syncForm();setView("editor")}
function loadDoc(id){const d=state.docs.find(x=>x.id===id); if(!d)return; state.current=JSON.parse(JSON.stringify(d)); state.current.items=(state.current.items||[]).map(it=>({id:it.id||uid("it"),desc:it.desc||"",qty:Number(it.qty||1),price:Number(it.price||0)})); state.activeDocId=id; setView("editor"); syncForm(); scrollTo({top:0,behavior:"smooth"})}
async function makePDF(){await saveDoc({forceNumber:true}); const {jsPDF}=window.jspdf; const docu=new jsPDF({unit:"pt",format:"letter"}); const cfg=state.cfg||defaultCfg(); let y=42; if(cfg.biz.logoDataUrl){try{docu.addImage(cfg.biz.logoDataUrl,"PNG",42,32,62,62); }catch{}} docu.setFont("helvetica","bold"); docu.setFontSize(18); docu.text(cfg.biz.name||"Nexus Invoicing",120,y); docu.setFont("helvetica","normal");docu.setFontSize(9); docu.text([cfg.biz.phone,cfg.biz.email,cfg.biz.addr].filter(Boolean).join(" · "),120,y+16); docu.setFont("helvetica","bold");docu.setFontSize(16);docu.text(state.current.type==="FAC"?"FACTURA":"COTIZACIÓN",430,y); docu.setFontSize(10);docu.text(state.current.number||"",430,y+18); y=125; docu.setFont("helvetica","bold");docu.text("Cliente",42,y);docu.setFont("helvetica","normal");docu.text(state.current.client.name||"",42,y+16);docu.text(state.current.client.contact||"",42,y+31);docu.text(state.current.client.addr||"",42,y+46);docu.text(`Fecha: ${state.current.date}`,430,y+16);docu.text(`Estado: ${state.current.status}`,430,y+31);
 const rows=(state.current.items||[]).map(it=>[it.desc,Number(it.qty||0).toFixed(2),money(it.price),money(Number(it.qty||0)*Number(it.price||0))]); docu.autoTable({startY:195,head:[["Descripción","Cant.","Precio","Total"]],body:rows,theme:"grid",styles:{fontSize:9,cellPadding:7},headStyles:{fillColor:[20,20,32]}}); y=docu.lastAutoTable.finalY+18; docu.setFont("helvetica","bold"); docu.text(`Subtotal: ${money(state.current.totals.sub)}`,390,y); docu.text(`IVU: ${money(state.current.totals.tax)}`,390,y+16); docu.text(`Total: ${money(state.current.totals.grand)}`,390,y+32); y+=64; docu.setFont("helvetica","normal"); docu.setFontSize(9); if(state.current.notes){docu.setFont("helvetica","bold");docu.text("Notas",42,y);docu.setFont("helvetica","normal");docu.text(docu.splitTextToSize(state.current.notes,500),42,y+14); y+=48} if(state.current.terms){docu.setFont("helvetica","bold");docu.text("Condiciones",42,y);docu.setFont("helvetica","normal");docu.text(docu.splitTextToSize(state.current.terms,500),42,y+14)} docu.save(`${state.current.number||"documento"}.pdf`)}

function refreshKPIs(){const docs=state.docs||[], customers=mergedCustomers(); const rev=docs.reduce((a,d)=>a+Number(d.totals?.grand||0),0); const pending=docs.filter(d=>d.status!=="PAGADA"&&d.status!=="CANCELADA").reduce((a,d)=>a+Number(d.totals?.grand||0),0);$("kpiCustomers").textContent=customers.length;$("kpiDocs").textContent=docs.length;$("kpiRevenue").textContent=money(rev);$("kpiPending").textContent=money(pending)}
function badge(status){return `<span class="badge ${status==="PAGADA"?"ok":status==="PENDIENTE"?"warn":""}">${clean(status||"—")}</span>`}
function renderDashboard(){const body=$("recentBody");body.innerHTML="";(state.docs||[]).slice(0,8).forEach(d=>{body.innerHTML+=`<tr><td>${clean(d.date)}</td><td>${clean(d.client?.name)}</td><td>${clean(d.number||d.type)}</td><td><strong>${money(d.totals?.grand)}</strong></td><td>${badge(d.status)}</td></tr>`}); if(!state.docs.length) body.innerHTML=`<tr><td colspan="5">Sin documentos.</td></tr>`; const list=$("sharedList");list.innerHTML="";mergedCustomers().slice(0,8).forEach(c=>{list.innerHTML+=`<div class="listItem"><strong>${clean(c.name)}</strong><small>${clean(c.contact||c.addr||"")} · ${clean(c.source||"shared")}</small></div>`}); if(!mergedCustomers().length) list.innerHTML=`<div class="listItem"><strong>Sin clientes</strong><small>Importa CRM o guarda un documento.</small></div>`}
function renderCustomers(){const q=norm($("customerSearch")?.value||$("globalSearch")?.value||"");const body=$("customersBody");body.innerHTML="";mergedCustomers().filter(c=>!q||[c.name,c.contact,c.addr,c.note].join(" ").toLowerCase().includes(q)).forEach(c=>{const tr=document.createElement("tr");tr.innerHTML=`<td><strong>${clean(c.name)}</strong><div class="muted">${clean(c.note||"")}</div></td><td>${clean(c.contact||"—")}</td><td>${clean(c.addr||"—")}</td><td>${clean(c.source||"—")}</td><td><button class="chip use">Usar</button> <button class="chip del">Borrar</button></td>`;tr.querySelector(".use").onclick=()=>{state.current=state.current||newDoc();state.current.client={name:c.name,contact:c.contact,addr:c.addr};setView("editor");syncForm()};tr.querySelector(".del").onclick=async()=>{if(!confirm("¿Borrar cliente?"))return; await Promise.allSettled([deleteDoc(doc(db,`${base(state.user.uid)}/customers/${c.id}`)),deleteDoc(doc(db,`${base(state.user.uid)}/shared_customers/items/${c.id}`))]); await loadAll()};body.appendChild(tr)}); if(!body.innerHTML) body.innerHTML=`<tr><td colspan="5">Sin resultados.</td></tr>`;renderDatalist()}
function renderHistory(){const q=norm($("globalSearch")?.value||"");const body=$("historyBody");body.innerHTML="";(state.docs||[]).filter(d=>!q||[d.number,d.client?.name,d.client?.contact].join(" ").toLowerCase().includes(q)).forEach(d=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${clean(d.date)}</td><td>${clean(d.number||"—")}</td><td>${clean(d.client?.name||"—")}</td><td><strong>${money(d.totals?.grand)}</strong></td><td>${badge(d.status)}</td><td><button class="chip open">Abrir</button></td>`;tr.querySelector(".open").onclick=()=>loadDoc(d.id);body.appendChild(tr)}); if(!body.innerHTML)body.innerHTML=`<tr><td colspan="6">Sin documentos.</td></tr>`}
function refreshAll(){setAuthUI();refreshKPIs();renderDashboard();renderCustomers();renderHistory();renderDatalist();if($("bizName")&&state.cfg){$("bizName").value=state.cfg.biz?.name||"";$("bizPhone").value=state.cfg.biz?.phone||"";$("bizEmail").value=state.cfg.biz?.email||"";$("bizAddr").value=state.cfg.biz?.addr||"";$("taxRate").value=state.cfg.taxRate||11.5}}
async function addCustomer(){if(!state.user)return alert("Login requerido."); const c={id:uid("cus"),name:$("cName").value.trim(),contact:$("cContact").value.trim(),addr:$("cAddr").value.trim(),note:$("cNote").value.trim(),source:"manual"}; if(!c.name)return alert("Nombre requerido."); await upsertSharedCustomer(c);["cName","cContact","cAddr","cNote"].forEach(id=>$(id).value=""); await loadAll()}
async function saveSettings(){if(!state.user)return alert("Login requerido."); const cfg=state.cfg||defaultCfg(); cfg.biz={name:$("bizName").value.trim(),phone:$("bizPhone").value.trim(),email:$("bizEmail").value.trim(),addr:$("bizAddr").value.trim(),logoUrl:cfg.biz?.logoUrl||"",logoDataUrl:cfg.biz?.logoDataUrl||""}; cfg.taxRate=Number($("taxRate").value||11.5); const file=$("bizLogo").files?.[0]; if(file){const r=ref(storage,`users/${state.user.uid}/nexus_logo_${Date.now()}_${file.name}`); await uploadBytes(r,file);cfg.biz.logoUrl=await getDownloadURL(r);cfg.biz.logoDataUrl=await fileToDataUrl(file)} const safe=JSON.parse(JSON.stringify(cfg)); if(safe.biz)safe.biz.logoDataUrl=""; await setDoc(settingsRef(state.user.uid),{...safe,updatedAt:serverTimestamp()},{merge:true}); state.cfg=cfg; alert("Guardado."); refreshAll()}
function exportCSV(rows,name){const csv=rows.map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function backup(){const payload={version:"nexus_invoicing_simplificado_v1",exportedAt:new Date().toISOString(),docs:state.docs,customers:mergedCustomers(),cfg:state.cfg}; const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download=`nexus_backup_${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function restore(file){if(!state.user||!file)return; const p=JSON.parse(await file.text()); if(p.cfg){state.cfg=p.cfg; await setDoc(settingsRef(state.user.uid),p.cfg,{merge:true})} for(const c of p.customers||[]) await upsertSharedCustomer(c); for(const d of p.docs||[]) await setDoc(doc(db,`${base(state.user.uid)}/docs/${d.id||uid("doc")}`),d,{merge:true}); await loadAll(); alert("Backup restaurado.")}
function bind(){document.querySelectorAll(".navBtn").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("btnLogin").onclick=login;$("btnLogout").onclick=logout;$("btnNewDoc").onclick=()=>{state.current=newDoc();state.activeDocId=null;setView("editor");syncForm()};$("btnAddItem").onclick=()=>{readForm();state.current.items.push({id:uid("it"),desc:"",qty:1,price:0});renderItems()};["docType","docNumber","docDate","docStatus","clientName","clientContact","clientAddr","notes","terms"].forEach(id=>$(id)?.addEventListener("input",()=>{if(id==="clientName")useCustomerByName();readForm()}));$("btnSaveDoc").onclick=()=>saveDoc();$("btnPDF").onclick=makePDF;$("btnDuplicate").onclick=duplicateDoc;$("btnDeleteDoc").onclick=deleteCurrentDoc;$("btnAddCustomer").onclick=addCustomer;$("btnImportCrm").onclick=importCrmCustomers;$("btnImportCrm2").onclick=importCrmCustomers;$("btnRefresh").onclick=loadAll;$("customerSearch").oninput=renderCustomers;$("globalSearch").oninput=()=>{renderCustomers();renderHistory()};$("btnSaveSettings").onclick=saveSettings;$("btnExportCustomers").onclick=()=>exportCSV([["Nombre","Contacto","Dirección","Origen"],...mergedCustomers().map(c=>[c.name,c.contact,c.addr,c.source])],`clientes_${today()}.csv`);$("btnExportDocs").onclick=()=>exportCSV([["Fecha","Número","Cliente","Total","Estado"],...state.docs.map(d=>[d.date,d.number,d.client?.name,d.totals?.grand,d.status])],`documentos_${today()}.csv`);$("btnBackup").onclick=backup;$("btnRestore").onclick=()=>$("restoreFile").click();$("restoreFile").onchange=e=>restore(e.target.files?.[0]);}
async function boot(){bind(); state.cfg=defaultCfg(); state.current=newDoc(); syncForm(); try{await getRedirectResult(auth)}catch{} onAuthStateChanged(auth,async u=>{state.user=u||null; setAuthUI(); if(u) await loadAll(); else{state.docs=[];state.customers=[];state.shared=[];refreshAll()}})}
document.addEventListener("DOMContentLoaded",boot);
